ARG RUBY_VERSION=3.4.7
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim AS base

ARG UID=1000
ARG GID=1000

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libvips pkg-config gnupg2 curl libyaml-dev

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y nodejs

RUN npm install -g yarn

ENV LANG=C.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3 \
  BUNDLE_PATH="/app/.bundle" \
  BUNDLE_INSTALL_FLAGS="--no-document" \
  YARN_CACHE_FOLDER="/app/.yarn-cache" \
  RUBOCOP_CACHE_ROOT="/app/.rubocop-cache"

RUN mkdir -p /app/node_modules /app/.bundle /app/.yarn-cache /app/.rubocop-cache
RUN chown -R ${UID}:${GID} /app/node_modules /app/.bundle /app/.yarn-cache /app/.rubocop-cache

USER ${UID}:${GID}


RUN gem update --system && gem install bundler

ENTRYPOINT ["bin/docker-entrypoint-dev"]

EXPOSE 3000

CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
