FROM ruby:3.3.1-slim

ARG UID=1000
ARG GID=1000

WORKDIR /app

RUN apt-get update -qq && apt-get install -yq --no-install-recommends \
    build-essential \
    gnupg2 \
    less \
    git \
    curl libjemalloc2 libvips sqlite3 \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV LANG=C.UTF-8 \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3 \
  BUNDLE_PATH="/app/.bundle" \
  BUNDLE_INSTALL_FLAGS="--no-document"

RUN mkdir -p /app/node_modules /app/.bundle
RUN chown -R ${UID}:${GID} /app/node_modules /app/.bundle

USER ${UID}:${GID}

RUN gem update --system && gem install bundler

ENTRYPOINT ["bin/docker-entrypoint-dev"]

EXPOSE 3000

CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
